### ISSUE TITLE
Feature Request: Tower Tombstone Hints

### ISSUE THREAD

**Issue by Landiie** [pseudoregalia-modding/rando#1]
hi! I played my first rando run of this and really enjoyed it, however, I see something that could be a great opportunity: Big key hints at the top of the tower on the tombstones being repurposed to be accurate to the area locations names of where the keys actually are located after shuffling. 

Would give more incentive to get to the top of the tower for another reason other than going to finish off the run! the TUNIC randomizer does this for the shrines, but with pseudoregalia, there are _actual_ hints to the big keys, while in TUNIC there is never officially any hints to get anything, so it could be even more lore-accurate here for.. brownie points or something idk

should probably be super vague to allow descriptions to be shared across multiple checks in one given area, i just chose random words for the example below

![pseudoregalia-Win64-Shipping_6bSqD3QZYN](https://github.com/pseudoregalia-modding/rando/assets/43101146/0127d7a9-3b07-4b17-a286-0d8f9e094dd3)

**Comment by bananaturtlesandwich** [comment]
this has finally been done in 828f5fe!
![hint](https://github.com/user-attachments/assets/a4a0630a-0cfc-4d84-8c5c-f974d9e719f0)

**Comment by Landiie** [comment]
Awesome, gives me an excuse to go back to it!! very excited thank you c:
